// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcUzytkownik.Data;

#nullable disable

namespace Silownia.Migrations
{
    [DbContext(typeof(MvcUzytkownikContext))]
    [Migration("20230531184747_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Silownia.Models.Karnet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("TEXT");

                    b.Property<int>("CzasTrwaniaWMiesiacach")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Karnet");
                });

            modelBuilder.Entity("Silownia.Models.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyAdministrator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyPracownik")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("KarnetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KarnetId");

                    b.ToTable("Uzytkownik");
                });

            modelBuilder.Entity("Silownia.Models.Wejscie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("CzasTrwania")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Wejscie");
                });

            modelBuilder.Entity("Silownia.Models.Uzytkownik", b =>
                {
                    b.HasOne("Silownia.Models.Karnet", "Karnet")
                        .WithMany("Uzytkownicy")
                        .HasForeignKey("KarnetId");

                    b.Navigation("Karnet");
                });

            modelBuilder.Entity("Silownia.Models.Wejscie", b =>
                {
                    b.HasOne("Silownia.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("Wejscia")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("Silownia.Models.Karnet", b =>
                {
                    b.Navigation("Uzytkownicy");
                });

            modelBuilder.Entity("Silownia.Models.Uzytkownik", b =>
                {
                    b.Navigation("Wejscia");
                });
#pragma warning restore 612, 618
        }
    }
}
